# Generated by Django 5.1.1 on 2024-12-01 00:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RunLogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='runmodel',
            name='lastedited',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
